name: catalog_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.3

dependencies:
  appsize: ^1.2.1
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^8.0.0
  go_router_flow: ^6.0.0+3
  http: ^0.13.5
  image_picker: ^0.8.6+1
  intl: ^0.17.0
  product_client:
    path: package/product_client
  product_repository:
    path: package/product_repository
  ui:
    path: package/ui

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
  generate: true
